### Install Necessary Libraries

In [1]:
!pip install colbert-ai[faiss-gpu,torch]
!pip install python-terrier
!pip install ir-datasets
!pip install numpy pandas scipy scikit-learn
!pip install transformers
!pip install sentence-transformers
!pip install ranx 
!pip install pytrec_eval
!pip install tqdm
!pip install datasets 
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

WARNING: The directory '/mnt/primary/launcher-cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
WARNING: Ignoring invalid distribution -orch (/mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages)
Requirement already satisfied: colbert-ai[faiss-gpu,torch] in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (0.2.22)
Requirement already satisfied: bitarray in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from colbert-ai[faiss-gpu,torch]) (3.6.1)
Requirement already satisfied: datasets in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from colbert-ai[faiss-gpu,torch]) (4.0.0)
Requirement already satisfied: flask in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from colbert-ai[faiss-gpu,torch]) (2.3.3)
Requirement already satisfied: GitPython in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from colbert-ai[faiss-gpu,torch]) (3.1.45)
Requirement already satisfied: python-dotenv in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from colbert-ai[faiss-gpu,torch]) (1.1.1)
Requirement already satisfied: ninja in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from colbert-ai[faiss-gpu,torch]) (1.13.0)
Requirement already satisfied: scipy in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from colbert-ai[faiss-gpu,torch]) (1.10.1)
Requirement already satisfied: tqdm in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from colbert-ai[faiss-gpu,torch]) (4.67.1)
Requirement already satisfied: transformers in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from colbert-ai[faiss-gpu,torch]) (4.21.0)
Requirement already satisfied: ujson in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from colbert-ai[faiss-gpu,torch]) (5.10.0)
Collecting torch==1.13.1 (from colbert-ai[faiss-gpu,torch])
  Downloading torch-1.13.1-cp39-cp39-manylinux1_x86_64.whl.metadata (24 kB)
Requirement already satisfied: faiss-gpu>=1.7.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from colbert-ai[faiss-gpu,torch]) (1.7.2)
Requirement already satisfied: typing-extensions in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from torch==1.13.1->colbert-ai[faiss-gpu,torch]) (4.14.1)
Collecting nvidia-cuda-runtime-cu11==11.7.99 (from torch==1.13.1->colbert-ai[faiss-gpu,torch])
  Downloading nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu11==8.5.0.96 (from torch==1.13.1->colbert-ai[faiss-gpu,torch])
  Downloading nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu11==11.10.3.66 (from torch==1.13.1->colbert-ai[faiss-gpu,torch])
  Downloading nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cuda-nvrtc-cu11==11.7.99 (from torch==1.13.1->colbert-ai[faiss-gpu,torch])
  Downloading nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: setuptools in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==1.13.1->colbert-ai[faiss-gpu,torch]) (78.1.1)
Requirement already satisfied: wheel in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==1.13.1->colbert-ai[faiss-gpu,torch]) (0.45.1)
Requirement already satisfied: filelock in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from datasets->colbert-ai[faiss-gpu,torch]) (3.19.1)
Requirement already satisfied: numpy>=1.17 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from datasets->colbert-ai[faiss-gpu,torch]) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from datasets->colbert-ai[faiss-gpu,torch]) (21.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from datasets->colbert-ai[faiss-gpu,torch]) (0.3.8)
Requirement already satisfied: pandas in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from datasets->colbert-ai[faiss-gpu,torch]) (2.3.1)
Requirement already satisfied: requests>=2.32.2 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from datasets->colbert-ai[faiss-gpu,torch]) (2.32.5)
Requirement already satisfied: xxhash in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from datasets->colbert-ai[faiss-gpu,torch]) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from datasets->colbert-ai[faiss-gpu,torch]) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->colbert-ai[faiss-gpu,torch]) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from datasets->colbert-ai[faiss-gpu,torch]) (0.34.4)
Requirement already satisfied: packaging in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from datasets->colbert-ai[faiss-gpu,torch]) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from datasets->colbert-ai[faiss-gpu,torch]) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->colbert-ai[faiss-gpu,torch]) (3.12.15)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->colbert-ai[faiss-gpu,torch]) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->colbert-ai[faiss-gpu,torch]) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->colbert-ai[faiss-gpu,torch]) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->colbert-ai[faiss-gpu,torch]) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->colbert-ai[faiss-gpu,torch]) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->colbert-ai[faiss-gpu,torch]) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->colbert-ai[faiss-gpu,torch]) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->colbert-ai[faiss-gpu,torch]) (1.20.1)
Requirement already satisfied: idna>=2.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->colbert-ai[faiss-gpu,torch]) (3.10)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from huggingface-hub>=0.24.0->datasets->colbert-ai[faiss-gpu,torch]) (1.1.8)
Requirement already satisfied: charset_normalizer<4,>=2 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from requests>=2.32.2->datasets->colbert-ai[faiss-gpu,torch]) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from requests>=2.32.2->datasets->colbert-ai[faiss-gpu,torch]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from requests>=2.32.2->datasets->colbert-ai[faiss-gpu,torch]) (2025.8.3)
Requirement already satisfied: Werkzeug>=2.3.7 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from flask->colbert-ai[faiss-gpu,torch]) (3.1.3)
Requirement already satisfied: Jinja2>=3.1.2 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from flask->colbert-ai[faiss-gpu,torch]) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from flask->colbert-ai[faiss-gpu,torch]) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from flask->colbert-ai[faiss-gpu,torch]) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from flask->colbert-ai[faiss-gpu,torch]) (1.9.0)
Requirement already satisfied: importlib-metadata>=3.6.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from flask->colbert-ai[faiss-gpu,torch]) (6.11.0)
Requirement already satisfied: zipp>=0.5 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->flask->colbert-ai[faiss-gpu,torch]) (3.21.0)
Requirement already satisfied: MarkupSafe>=2.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from Jinja2>=3.1.2->flask->colbert-ai[faiss-gpu,torch]) (3.0.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from GitPython->colbert-ai[faiss-gpu,torch]) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from gitdb<5,>=4.0.1->GitPython->colbert-ai[faiss-gpu,torch]) (5.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from pandas->datasets->colbert-ai[faiss-gpu,torch]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from pandas->datasets->colbert-ai[faiss-gpu,torch]) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from pandas->datasets->colbert-ai[faiss-gpu,torch]) (2025.2)
Requirement already satisfied: six>=1.5 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->datasets->colbert-ai[faiss-gpu,torch]) (1.17.0)
Requirement already satisfied: regex!=2019.12.17 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from transformers->colbert-ai[faiss-gpu,torch]) (2025.7.34)
Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from transformers->colbert-ai[faiss-gpu,torch]) (0.12.1)
Downloading torch-1.13.1-cp39-cp39-manylinux1_x86_64.whl (887.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.4/887.4 MB 287.0 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 287.5 MB/s eta 0:00:00a 0:00:01
Downloading nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl (21.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 291.0 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 485.0 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 293.7 MB/s eta 0:00:00a 0:00:01
WARNING: Ignoring invalid distribution -orch (/mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages)
Installing collected packages: nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cublas-cu11, nvidia-cudnn-cu11, torch
  Attempting uninstall: nvidia-cuda-runtime-cu11
    Found existing installation: nvidia-cuda-runtime-cu11 11.8.89
    Uninstalling nvidia-cuda-runtime-cu11-11.8.89:
      Successfully uninstalled nvidia-cuda-runtime-cu11-11.8.890m [nvidia-cuda-runtime-cu11]
  Attempting uninstall: nvidia-cuda-nvrtc-cu11━━ 0/5 [nvidia-cuda-runtime-cu11]
    Found existing installation: nvidia-cuda-nvrtc-cu11 11.8.89nvidia-cuda-runtime-cu11]
    Uninstalling nvidia-cuda-nvrtc-cu11-11.8.89: 0/5 [nvidia-cuda-runtime-cu11]
      Successfully uninstalled nvidia-cuda-nvrtc-cu11-11.8.89 [nvidia-cuda-runtime-cu11]
  Attempting uninstall: nvidia-cublas-cu11━━━━━━━━━━━━━━━━━━━━━━━━ 1/5 [nvidia-cuda-nvrtc-cu11]
    Found existing installation: nvidia-cublas-cu11 11.11.3.6━ 1/5 [nvidia-cuda-nvrtc-cu11]
    Uninstalling nvidia-cublas-cu11-11.11.3.6:━━━━━━━━━━━━━━━━━━━━ 2/5 [nvidia-cublas-cu11]
      Successfully uninstalled nvidia-cublas-cu11-11.11.3.6━━━━━━━ 2/5 [nvidia-cublas-cu11]
  Attempting uninstall: nvidia-cudnn-cu110m━━━━━━━━━━━━━━━━━━━━━━━ 2/5 [nvidia-cublas-cu11]
    Found existing installation: nvidia-cudnn-cu11 9.1.0.70━━━ 2/5 [nvidia-cublas-cu11]
    Uninstalling nvidia-cudnn-cu11-9.1.0.70:━━━━━━━━━━━━━━━━━━ 2/5 [nvidia-cublas-cu11]
      Successfully uninstalled nvidia-cudnn-cu11-9.1.0.70━━━━━ 2/5 [nvidia-cublas-cu11]
   ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━ 3/5 [nvidia-cudnn-cu11]  WARNING: Failed to remove contents in a temporary directory '/mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages/nvidia/~1dnn'.
  You can safely remove it manually.
  Attempting uninstall: torch
    Found existing installation: torch 2.7.1+cu118━━━━━━━━━━━━ 3/5 [nvidia-cudnn-cu11]
    Uninstalling torch-2.7.1+cu118:━━━━━╺━━━━━━━ 4/5 [torch]nn-cu11]
      Successfully uninstalled torch-2.7.1+cu118m╺━━━━━━━ 4/5 [torch]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━ 4/5 [torch]  WARNING: Failed to remove contents in a temporary directory '/mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages/~3rch'.
  You can safely remove it manually.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [torch]32m4/5 [torch]
WARNING: Ignoring invalid distribution -orch (/mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.1.0 requires transformers<5.0.0,>=4.41.0, but you have transformers 4.21.0 which is incompatible.
torchaudio 2.7.1+cu118 requires torch==2.7.1, but you have torch 1.13.1 which is incompatible.
torchvision 0.22.1+cu118 requires torch==2.7.1, but you have torch 1.13.1 which is incompatible.
Successfully installed nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 torch-1.13.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
WARNING: The directory '/mnt/primary/launcher-cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
WARNING: Ignoring invalid distribution -orch (/mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages)
Requirement already satisfied: python-terrier in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (0.13.1)
Requirement already satisfied: numpy in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (1.26.4)
Requirement already satisfied: pandas in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (2.3.1)
Requirement already satisfied: more-itertools in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (10.7.0)
Requirement already satisfied: tqdm in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (4.67.1)
Requirement already satisfied: requests in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (2.32.5)
Requirement already satisfied: ir-datasets>=0.3.2 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (0.5.9)
Requirement already satisfied: pyjnius>=1.4.2 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (1.6.1)
Requirement already satisfied: deprecated in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (1.2.18)
Requirement already satisfied: scipy in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (1.10.1)
Requirement already satisfied: ir-measures>=0.3.1 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (0.4.1)
Requirement already satisfied: pytrec-eval-terrier>=0.5.3 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (0.5.7)
Requirement already satisfied: jinja2 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (3.1.6)
Requirement already satisfied: statsmodels in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (0.14.5)
Requirement already satisfied: dill in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (0.3.8)
Requirement already satisfied: joblib in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (1.5.1)
Requirement already satisfied: chest in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (0.2.3)
Requirement already satisfied: lz4 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from python-terrier) (4.4.4)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from ir-datasets>=0.3.2->python-terrier) (4.13.4)
Requirement already satisfied: inscriptis>=2.2.0 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from ir-datasets>=0.3.2->python-terrier) (2.6.0)
Requirement already satisfied: lxml>=4.5.2 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from ir-datasets>=0.3.2->python-terrier) (6.0.0)
Requirement already satisfied: pyyaml>=5.3.1 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from ir-datasets>=0.3.2->python-terrier) (6.0.2)
Requirement already satisfied: trec-car-tools>=2.5.4 in /mnt/primary/conda-envs/colbertv2/lib/python3.9/site-packages (from ir-datasets>=0.3.2->python-terrier) (2.6)

### Import Necessary libraries

In [2]:
import os
import torch
import numpy as np
import ir_datasets
import pandas as pd
import pyterrier as pt
from colbert import Searcher
from scipy.sparse import csr_matrix
from colbert.infra import Run, RunConfig
from transformers import AutoTokenizer, AutoModelForMaskedLM

/opt/miniconda3/envs/colbertv2/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# Initialize PyTerrier
if not pt.java.started():
    pt.java.init()

Java started and loaded: pyterrier.java, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]

### Load Dataset

In [16]:
# Load the SARA dataset from ir_datasets
dataset = ir_datasets.load('sara')

# Extract queries and relevance judgments into lists
topics_list = list(dataset.queries_iter())
qrels_list = list(dataset.qrels_iter())

# Collect all document texts
docs = list(dataset.docs_iter())
doc_texts = {doc.doc_id: doc.text for doc in docs}

# Convert queries to a PyTerrier-compatible DataFrame
topics = pd.DataFrame([
    {'qid': topic.query_id, 'query': topic.text} 
    for topic in topics_list
])

# Convert qrels (relevance judgments) to a PyTerrier-compatible DataFrame
qrels = pd.DataFrame([
    {'qid': qrel.query_id, 'docno': str(qrel.doc_id), 'label': int(qrel.relevance)}
    for qrel in qrels_list
])

# Print dataset statistics
print(f"No. of Queries: {len(topics)},  No. of Documents: {len(docs)}, Total Qrels: {len(qrels)}")

No. of Queries: 150,  No. of Documents: 1702, Total Qrels: 34413

### Setting Up Document ID Mapping

In [17]:
# Load the document ID mapping
index_name = 'colbert_sara_index'
mapping_path = f"./Index/{index_name}_doc_mapping.txt"

print(f"Document ID mapping from: {mapping_path} loaded ")
if not os.path.exists(mapping_path):
    raise FileNotFoundError(f"Mapping file not found: {mapping_path}")

# Load mapping: ColBERT index -> SARA doc ID
idx_to_doc_id = {}
with open(mapping_path, 'r', encoding='utf-8') as f:
    for line in f:
        parts = line.strip().split('\t')
        if len(parts) == 2:
            idx, doc_id = parts
            idx_to_doc_id[int(idx)] = doc_id

print(f"Mapping for {len(idx_to_doc_id)} documents loaded \n")
print(f"Sample mappings: {dict(list(idx_to_doc_id.items())[:3])}")

Document ID mapping from: ./Index/colbert_sara_index_doc_mapping.txt loaded
Mapping for 1702 documents loaded

Sample mappings: {0: '114715', 1: '229405', 2: '232795'}

### Load ColBERT Retrieval Model

In [18]:
# Load the ColBERT index
print("Loading ColBERT searcher")

with Run().context(RunConfig(experiment='sara_experiment')):
    searcher = Searcher(index=index_name, checkpoint="colbert-ir/colbertv2.0")
    print("Searcher loaded successfully")

Loading ColBERT searcher
[Sep 08, 14:56:12] #> Loading codec...
[Sep 08, 14:56:12] #> Loading IVF...
[Sep 08, 14:56:12] #> Loading doclens...

/opt/miniconda3/envs/colbertv2/lib/python3.9/site-packages/colbert/utils/amp.py:12: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler()
100%|██████████| 1/1 [00:00<00:00, 1285.02it/s]

[Sep 08, 14:56:12] #> Loading codes and residuals...

100%|██████████| 1/1 [00:00<00:00, 69.79it/s]

Searcher loaded successfully

### Load Splade Retrieval Model

In [19]:
# Load SPLADEv2 model and tokenizer
splade_model_name = "naver/splade-cocondenser-ensembledistil"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
splade_tokenizer = AutoTokenizer.from_pretrained(splade_model_name)
splade_model = AutoModelForMaskedLM.from_pretrained(splade_model_name).to(device)

# Set to evaluation mode
splade_model.eval()

BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (cls): BertOnlyMLMHead(
    (predictions): BertLMPredictionHead(
      (transform): BertPredictionHeadTransform(
        (dense): Linear(in_features=768, out_features=768, bias=True)
        (transform_act_fn): GELUActivation()
        (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      )
      (decoder): Linear(in_features=768, out_features=30522, bias=True)
    )
  )
)

### Document Encoding and Retrieval Functions 
##### Top K documents retrieved by ColBERT are re-ranked by SPLADE

In [20]:
def encode_splade(text, tokenizer, model, max_length=512):

    # Tokenize input text
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=max_length).to(device)
    
    # Generate SPLADE representation without gradient computation
    with torch.no_grad():
        
        logits = model(**inputs).logits
        # SPLADE log(1 + relu(x)) sparse encoding
        sparse_rep = torch.log(1 + torch.relu(logits)) * inputs.attention_mask.unsqueeze(-1)
        sparse_rep = torch.max(sparse_rep, dim=1)[0]  # max pooling over sequence length
        
    return sparse_rep.cpu().numpy()

def compute_splade_similarity(query_rep, doc_rep):
    "Compute similarity between SPLADE representations"
    
    # Convert to sparse matrices for efficient computation
    query_sparse = csr_matrix(query_rep)
    doc_sparse = csr_matrix(doc_rep)
    
    # Compute dot product
    similarity = query_sparse.dot(doc_sparse.T).toarray()[0, 0]
    return float(similarity)

def retrieve_and_rerank(topics_df, k_colbert=100, k_rerank=100):
    "Retrieve with ColBERT and re-rank top results with SPLADE v2"
    final_results = []
    
    print(f"Running ColBERT + SPLADE v2 pipeline for {len(topics_df)} queries...")
    
    for i, (_, row) in enumerate(topics_df.iterrows()):
        if i % 10 == 0:
            print(f"Processing query {i+1}/{len(topics_df)}")
            
        qid = row['qid']
        query = row['query']
        
        try:
            # ColBERT retrieval
            pids, ranks, scores = searcher.search(query, k=k_colbert)
            
            # Get top k results for re-ranking
            colbert_results = []
            for rank, (pid, score) in enumerate(zip(pids[:k_rerank], scores[:k_rerank])):
                if pid in idx_to_doc_id:
                    original_doc_id = idx_to_doc_id[pid]
                    if original_doc_id in doc_texts:
                        colbert_results.append({
                            'doc_id': original_doc_id,
                            'text': doc_texts[original_doc_id],
                            'colbert_score': float(score),
                            'colbert_rank': rank
                        })
            
            if not colbert_results:
                print(f"No valid results for query {qid}")
                continue
            
            # SPLADE v2 re-ranking
            print(f"  Re-ranking top {len(colbert_results)} results with SPLADE v2...")
            
            # Encode query with SPLADE
            query_rep = encode_splade(query, splade_tokenizer, splade_model)
            
            # Encode documents and compute similarities
            splade_results = []
            for result in colbert_results:
                doc_rep = encode_splade(result['text'], splade_tokenizer, splade_model)
                splade_score = compute_splade_similarity(query_rep, doc_rep)
                
                splade_results.append({
                    'doc_id': result['doc_id'],
                    'splade_score': splade_score,
                    'colbert_score': result['colbert_score'],  # Keep for reference
                    'colbert_rank': result['colbert_rank']
                })
            
            # Sort by SPLADE score
            splade_results.sort(key=lambda x: x['splade_score'], reverse=True)
            
            # Add to final results with SPLADE ranking
            for rank, result in enumerate(splade_results):
                final_results.append({
                    'qid': qid,
                    'docno': str(result['doc_id']),
                    'score': result['splade_score'],
                    'colbert_score': result['colbert_score'],
                    'splade_score': result['splade_score'],
                    'colbert_rank': result['colbert_rank'],
                    'rank': rank  # New SPLADE ranking
                })
            
        except Exception as e:
            print(f"Error processing query {qid}: {e}")
            continue
    
    # Convert to DataFrame
    results_df = pd.DataFrame(final_results)
        
    return results_df

In [23]:
# Run the pipeline
scores = retrieve_and_rerank(topics, k_colbert=100, k_rerank=100)
print(f"Retrieved and re-ranked {len(scores)} results")

if len(scores) == 0:
    print("ERROR: No results retrieved! Check your pipeline.")
    exit(1)

Running ColBERT + SPLADE v2 pipeline for 150 queries...
Processing query 1/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 11/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 21/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 31/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 41/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 51/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 61/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 71/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 81/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 91/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 101/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 111/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 121/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 131/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Processing query 141/150
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
  Re-ranking top 100 results with SPLADE v2...
Retrieved and re-ranked 15000 results

In [ ]:
scores.to_csv("./retrieval_scores/colbert+splade_scores.csv")

In [25]:
print(scores.shape)
scores.head()

(15000, 7)

  qid   docno     score  colbert_score  splade_score  colbert_rank  rank
0   1  120514  6.148230      10.804688      6.148230             3     0
1   1  175162  6.029339       8.593750      6.029339            36     1
2   1    6178  5.775954       8.117188      5.775954            49     2
3   1  177853  5.539324       9.828125      5.539324            10     3
4   1  176650  5.378632       9.703125      5.378632            12     4

### Evaluation

In [26]:
# Evaluate with PyTerrier
scores['docno'] = scores['docno'].astype(str)
qrels['docno'] = qrels['docno'].astype(str)

metrics = ['ndcg_cut_10', 'map', 'P_10', 'recall_10']
eval_results = pt.Evaluate(scores, qrels, metrics=metrics)

print("\nEvaluation")

Evaluation

In [28]:
results = pd.DataFrame(eval_results, index=[0])
results = results.round(4)

# Add model column
results.insert(0, "Model", "ColBERT+SPLADE")

In [29]:
results

            Model  ndcg_cut_10     map    P_10  recall_10
0  ColBERT+SPLADE       0.1513  0.0889  0.1347     0.1227